name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: loui3/hornlog-client:latest

    - name: Webhook POST Action
      uses: muinmomin/webhook-action@v1.0.0
      with:
        url: https://portainer.nas.dewwwe.com/api/webhooks/2597a7fc-e7f6-46a0-9771-958432412d19